approved = [
  "mit",
  "apache-2.0",
  "bsd-3-clause",
  "bsd-2-clause",
  "mpl-2.0",
  "isc"
]

ignored = [
  "github.com/ghodss/yaml", # MIT - https://github.com/ghodss/yaml/blob/master/LICENSE
  "sigs.k8s.io/yaml", # MIT - https://github.com/kubernetes-sigs/yaml/blob/master/LICENSE
  "go.mongodb.org/mongo-driver", # Apache 2.0 - https://github.com/mongodb/mongo-go-driver/blob/master/LICENSE
  "github.com/xeipuuv/gojsonpointer", # Apache 2.0 - https://github.com/xeipuuv/gojsonpointer/blob/master/LICENSE-APACHE-2.0.txt
  "github.com/xeipuuv/gojsonreference", # Apache 2.0 - https://github.com/xeipuuv/gojsonreference/blob/master/LICENSE-APACHE-2.0.txt
  "github.com/xeipuuv/gojsonschema", # Apache 2.0 - https://github.com/xeipuuv/gojsonschema/blob/master/LICENSE-APACHE-2.0.txt
  "github.com/russross/blackfriday/v2", # Simplified BSD License - https://github.com/russross/blackfriday/blob/master/LICENSE.txt
  "github.com/gogo/protobuf", # BSD-3-Clause - https://pkg.go.dev/github.com/gogo/protobuf?tab=licenses
  "google.golang.org/protobuf", # BSD-3-Clause - https://pkg.go.dev/google.golang.org/protobuf?tab=licenses
  "github.com/TykTechnologies/gojsonschema", # Apache 2.0 - https://github.com/TykTechnologies/gojsonschema/blob/master/LICENSE-APACHE-2.0.txt
  "github.com/eclipse/paho.mqtt.golang", # Eclipse Public License - v 2.0 - https://github.com/eclipse/paho.mqtt.golang/blob/master/LICENSE
  "github.com/jensneuse/abstractlogger", # no license file
  "github.com/lonelycode/go-uuid", # 3-Clause BSD License - https://github.com/lonelycode/go-uuid/blob/master/uuid/LICENSE
  "github.com/jensneuse/byte-template", # no license file
]

[header]
ignorePaths = ["api", "plugins/api"]
#ignoreFiles = ["zz_generated.*.go"]
template = """// Copyright © :YEAR: Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License."""