apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "apiclarity-postgresql" "existingSecret" }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "apiclarity.labels" . }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
data:
  postgresql-password: {{ .Values.global.databasePassword | b64enc }}
